name: CI
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olafurpg/setup-scala@v11
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Compile
        run: sbt compile
      - name: Check code formatting
        run: sbt scalafmtCheckAll
      - name: Run unit tests
        run: sbt test
      - name: Run integration tests
        run: sbt scripted
